import type { InvestigationTree } from "@/lib/api/types";

/** Test-only fixture mirroring the investigator's flat tree payload. */
export const TREE_FIXTURE: InvestigationTree = {
  root_id: "root",
  nodes: [
    {
      id: "root",
      parent_id: null,
      kind: "root",
      statement: "Revenue declined 11.8% in August 2026 vs July 2026",
      statement_type: "observation",
      metric_id: "revenue",
      metric_format: "currency",
      current: 3_700_000,
      baseline: 4_195_000,
      abs_change: -495_000,
      pct_change: -0.118,
      evidence_strength: "strong",
      evidence_reasons: ["Direct calculation"],
      artifact_ids: ["a1"],
      status: "proposed",
      children: ["units", "asp"],
    },
    {
      id: "units",
      parent_id: "root",
      kind: "driver",
      statement: "Unit volume declined 8.2%",
      statement_type: "supported_explanation",
      pct_change: -0.082,
      contribution_to_parent: { effect: -330000, share: 0.67, method: "lmdi" },
      evidence_strength: "strong",
      evidence_reasons: [],
      artifact_ids: [],
      status: "confirmed",
      children: ["dallas", "austin"],
    },
    {
      id: "dallas",
      parent_id: "units",
      kind: "segment",
      statement: "Dallas -19.4%",
      statement_type: "supported_explanation",
      segment: { dimension: "branch", value: "Dallas" },
      pct_change: -0.194,
      contribution_to_parent: { effect: -200000, share: 0.54, method: "additive" },
      evidence_strength: "moderate",
      evidence_reasons: [],
      artifact_ids: [],
      status: "proposed",
      children: [],
    },
    {
      id: "austin",
      parent_id: "units",
      kind: "segment",
      statement: "Austin +2.8%",
      statement_type: "observation",
      pct_change: 0.028,
      contribution_to_parent: -0.05,
      evidence_strength: "weak",
      evidence_reasons: [],
      artifact_ids: [],
      status: "rejected",
      children: [],
    },
    {
      id: "asp",
      parent_id: "root",
      kind: "hypothesis",
      statement: "Promotional discounting may have lowered price",
      statement_type: "hypothesis",
      evidence_strength: "hypothesis_only",
      evidence_reasons: [],
      artifact_ids: [],
      status: "proposed",
      children: [],
    },
  ],
};
