"""Read-only SQL enforcement.

:func:`ensure_read_only` parses SQL with sqlglot in the target dialect and only
lets a *single* query statement through (``SELECT``, set operations, ``VALUES``,
optionally wrapped in ``WITH``). Everything else is rejected with
:class:`UnsafeSQLError`:

* multiple statements (including statements hidden after comments),
* DDL / DML anywhere in the tree (also inside CTEs, e.g. ``WITH x AS (DELETE ...)``),
* ``SELECT ... INTO`` and locking clauses (``FOR UPDATE``),
* ``COPY``, ``ATTACH``/``DETACH``, ``INSTALL``/``LOAD``, ``PRAGMA``, ``SET``, ``USE``,
  ``EXPORT``/``IMPORT``, ``CALL``/``EXEC``, transactions and any statement sqlglot
  cannot parse into a query (``exp.Command``),
* file, network, shell and session-mutating functions (``read_csv``, ``read_parquet``,
  ``glob``, ``query``, ``getenv``, ``pg_read_file``, ``set_config``, ``xp_cmdshell``,
  ``load_file``, ``openrowset``, ``nextval`` ...),
* file paths or URLs used as table names (DuckDB replacement scans such as
  ``SELECT * FROM 'data.csv'``),
* MySQL executable comments (``/*! ... */``).

The function returns SQL *regenerated by sqlglot* from the validated tree, so the
text that runs is exactly the text that was checked (no parser differentials).
"""

from __future__ import annotations

import re
from collections.abc import Iterable

import sqlglot
from sqlglot import exp
from sqlglot.errors import ParseError, TokenError

__all__ = [
    "UnsafeSQLError",
    "ensure_read_only",
    "is_read_only",
    "BLOCKED_FUNCTIONS",
    "DUCKDB_BLOCKED_FUNCTIONS",
    "TABLE_FUNCTION_ALLOWLIST",
    "referenced_tables",
]


class UnsafeSQLError(ValueError):
    """SQL was rejected by the read-only policy."""

    def __init__(self, message: str, *, code: str = "unsafe_sql") -> None:
        super().__init__(message)
        self.code = code


# Lower-case function names that are never allowed in user SQL.
BLOCKED_FUNCTIONS: frozenset[str] = frozenset(
    {
        # DuckDB file / external access and SQL-in-a-string
        "read_csv",
        "read_csv_auto",
        "read_parquet",
        "parquet_scan",
        "parquet_metadata",
        "parquet_schema",
        "parquet_file_metadata",
        "parquet_kv_metadata",
        "read_json",
        "read_json_auto",
        "read_json_objects",
        "read_json_objects_auto",
        "read_ndjson",
        "read_ndjson_auto",
        "read_ndjson_objects",
        "read_text",
        "read_blob",
        "read_xlsx",
        "read_xlsx_auto",
        "sniff_csv",
        "glob",
        "csv_scan",
        "delta_scan",
        "iceberg_scan",
        "iceberg_metadata",
        "iceberg_snapshots",
        "st_read",
        "st_read_meta",
        "sqlite_scan",
        "sqlite_attach",
        "sqlite_query",
        "postgres_scan",
        "postgres_scan_pushdown",
        "postgres_attach",
        "postgres_query",
        "postgres_execute",
        "mysql_scan",
        "mysql_query",
        "mysql_execute",
        "query",
        "query_table",
        "getenv",
        "http_get",
        "http_post",
        "httpfs",
        "load_extension",
        "install_extension",
        "duckdb_secrets",
        "which_secret",
        "from_substrait",
        "from_substrait_json",
        # PostgreSQL
        "pg_read_file",
        "pg_read_binary_file",
        "pg_ls_dir",
        "pg_stat_file",
        "pg_ls_logdir",
        "pg_ls_waldir",
        "pg_ls_tmpdir",
        "pg_ls_archive_statusdir",
        "lo_import",
        "lo_export",
        "lo_from_bytea",
        "lo_put",
        "lo_unlink",
        "lo_create",
        "lo_creat",
        "set_config",
        "pg_terminate_backend",
        "pg_cancel_backend",
        "pg_reload_conf",
        "pg_rotate_logfile",
        "pg_sleep",
        "pg_sleep_for",
        "pg_sleep_until",
        "pg_advisory_lock",
        "pg_advisory_xact_lock",
        "pg_try_advisory_lock",
        "pg_promote",
        "pg_switch_wal",
        "pg_create_restore_point",
        "pg_start_backup",
        "pg_stop_backup",
        "pg_backup_start",
        "pg_backup_stop",
        "pg_logical_emit_message",
        "pg_create_logical_replication_slot",
        "pg_drop_replication_slot",
        "txid_current",
        "nextval",
        "setval",
        "currval",
        "dblink",
        "dblink_exec",
        "dblink_connect",
        "dblink_send_query",
        "query_to_xml",
        "query_to_xml_and_xmlschema",
        "table_to_xml",
        "cursor_to_xml",
        # MySQL
        "load_file",
        "sleep",
        "benchmark",
        "get_lock",
        "release_lock",
        "sys_exec",
        "sys_eval",
        # SQL Server
        "xp_cmdshell",
        "xp_dirtree",
        "xp_fileexist",
        "xp_regread",
        "openrowset",
        "opendatasource",
        "openquery",
        "openxml",
        "waitfor",
        # BigQuery / Snowflake
        "external_query",
        "system$wait",
        "get_presigned_url",
        "build_scoped_file_url",
        "build_stage_file_url",
        "get_stage_location",
    }
)

# DuckDB-only: SQL-in-a-string, storage maintenance, settings and catalogue introspection
# (``duckdb_databases()`` and ``current_setting('temp_directory')`` reveal server paths).
DUCKDB_BLOCKED_FUNCTIONS: frozenset[str] = frozenset(
    {
        "json_execute_serialized_sql",
        "json_serialize_sql",
        "json_deserialize_sql",
        "json_serialize_plan",
        "checkpoint",
        "force_checkpoint",
        "current_setting",
        "getvariable",
        "set_variable",
        "enable_profiling",
        "disable_profiling",
    }
)
_DUCKDB_BLOCKED_PREFIXES = ("duckdb_", "pragma_", "json_execute")

# Functions allowed in FROM / LATERAL position. Everything else that produces a table from a
# function call (catalogue scans, SQL-in-a-string, file readers) is refused, so a new DuckDB
# table function is blocked until it is reviewed.
TABLE_FUNCTION_ALLOWLIST: frozenset[str] = frozenset(
    {"range", "generate_series", "unnest", "generate_subscripts"}
)

_BLOCKED_PREFIXES = (
    "pg_read",
    "pg_ls_",
    "lo_",
    "xp_",
    "sp_",
    "system$",
    "dblink",
    "read_",
    "st_read",
    "pg_file",
)

# sqlglot classes that represent dangerous functions regardless of spelling.
_BLOCKED_FUNC_CLASSES: tuple[type[exp.Expression], ...] = tuple(
    cls
    for cls in (getattr(exp, n, None) for n in ("ReadCSV", "ReadParquet", "ReadJSON", "Getenv"))
    if isinstance(cls, type)
)

_FORBIDDEN_NODE_NAMES = (
    "Insert",
    "Update",
    "Delete",
    "Merge",
    "Create",
    "Drop",
    "Alter",
    "AlterTable",
    "AlterColumn",
    "RenameTable",
    "TruncateTable",
    "Command",
    "Copy",
    "Attach",
    "Detach",
    "Install",
    "Load",
    "LoadData",
    "Pragma",
    "Set",
    "SetItem",
    "Use",
    "Transaction",
    "Commit",
    "Rollback",
    "Describe",
    "Show",
    "Summarize",
    "Grant",
    "Revoke",
    "Kill",
    "Analyze",
    "Cache",
    "Uncache",
    "Refresh",
    "Export",
    "Into",
    "Lock",
    "Execute",
    "ExecuteSql",
    "Declare",
    "DeclareItem",
    "Comment",
    "Vacuum",
    "Checkpoint",
    "Call",
)
_FORBIDDEN_NODES: tuple[type[exp.Expression], ...] = tuple(
    cls for cls in (getattr(exp, n, None) for n in _FORBIDDEN_NODE_NAMES) if isinstance(cls, type)
)

_ALLOWED_ROOTS: tuple[type[exp.Expression], ...] = tuple(
    cls
    for cls in (
        getattr(exp, n, None) for n in ("Select", "Union", "Intersect", "Except", "SetOperation", "Values")
    )
    if isinstance(cls, type)
)

_FILE_LIKE_RE = re.compile(
    r"(://|^[~/\\]|\\|/|\.(csv|tsv|txt|parquet|json|jsonl|ndjson|xlsx|xls|gz|zst|bz2|db|duckdb|sqlite|arrow|avro|orc)$)",
    re.IGNORECASE,
)

_DIALECT_ALIASES = {
    "postgresql": "postgres",
    "mssql": "tsql",
    "sqlserver": "tsql",
    "sql_server": "tsql",
    "mariadb": "mysql",
}


def _dialect(dialect: str) -> str:
    d = (dialect or "duckdb").lower()
    return _DIALECT_ALIASES.get(d, d)


def _func_name(node: exp.Expression | exp.Func) -> str:
    if isinstance(node, exp.Anonymous):
        return str(node.name).lower()
    if isinstance(node, exp.Func):
        try:
            return node.sql_name().lower()
        except Exception:  # pragma: no cover - sqlglot internals
            return type(node).__name__.lower()
    return ""


def _is_blocked_function(name: str, allow: frozenset[str], dialect: str = "duckdb") -> bool:
    if not name or name in allow:
        return False
    if name in BLOCKED_FUNCTIONS:
        return True
    if dialect == "duckdb" and (
        name in DUCKDB_BLOCKED_FUNCTIONS or name.startswith(_DUCKDB_BLOCKED_PREFIXES)
    ):
        return True
    return name.startswith(_BLOCKED_PREFIXES)


def _check_table_function(node: exp.Expression, allow: frozenset[str]) -> None:
    """A function used as a table (``FROM f(...)`` or ``LATERAL f(...)``) must be allowlisted."""
    fn = node.this if isinstance(node, exp.Table | exp.Lateral) else None
    if isinstance(fn, exp.Func | exp.Anonymous):
        name = _func_name(fn)
        if name not in TABLE_FUNCTION_ALLOWLIST and name not in allow:
            raise UnsafeSQLError(f"table function {name} is not allowed", code="blocked_function")


def _check_table(table: exp.Table, dialect: str = "duckdb") -> None:
    ident = table.this
    if dialect == "duckdb" and table.name and table.name.lower().startswith(_DUCKDB_BLOCKED_PREFIXES):
        raise UnsafeSQLError(f"system table {table.name} is not allowed", code="blocked_function")
    if isinstance(ident, exp.Literal) and ident.is_string:
        raise UnsafeSQLError(f"string literals cannot be used as tables ({ident.this!r})", code="file_access")
    parts = [p for p in (table.name, table.args.get("db"), table.args.get("catalog")) if p is not None]
    for part in parts:
        text = part.name if isinstance(part, exp.Expression) else str(part)
        if text and _FILE_LIKE_RE.search(text):
            raise UnsafeSQLError(
                f"file paths and URLs cannot be used as tables ({text!r})", code="file_access"
            )


def ensure_read_only(
    sql: str,
    dialect: str = "duckdb",
    *,
    allow_functions: Iterable[str] = (),
    max_length: int = 1_000_000,
) -> str:
    """Validate that ``sql`` is a single read-only query and return it normalised.

    ``allow_functions`` lets trusted internal callers re-enable specific blocked
    functions; user-facing code paths never pass it.
    """
    if not isinstance(sql, str):
        raise UnsafeSQLError("SQL must be a string", code="invalid")
    if len(sql) > max_length:
        raise UnsafeSQLError(f"SQL is longer than {max_length} characters", code="too_long")
    text = sql.strip()
    if not text:
        raise UnsafeSQLError("SQL is empty", code="empty")
    if "/*!" in text:
        raise UnsafeSQLError(
            "MySQL executable comments (/*! ... */) are not allowed", code="executable_comment"
        )
    if "\x00" in text:
        raise UnsafeSQLError("NUL bytes are not allowed in SQL", code="invalid")
    d = _dialect(dialect)
    allow = frozenset(f.lower() for f in allow_functions)
    try:
        statements = [s for s in sqlglot.parse(text, read=d) if s is not None]
    except (ParseError, TokenError) as exc:
        raise UnsafeSQLError(f"could not parse SQL: {_first_line(exc)}", code="parse_error") from exc
    except ValueError as exc:  # unknown dialect
        raise UnsafeSQLError(f"could not parse SQL: {exc}", code="parse_error") from exc
    if not statements:
        raise UnsafeSQLError("SQL contains no statement", code="empty")
    if len(statements) > 1:
        raise UnsafeSQLError(
            f"only a single statement is allowed (found {len(statements)})", code="multiple_statements"
        )
    stmt = statements[0]
    root = stmt
    while isinstance(root, exp.Subquery | exp.Paren):
        root = root.this
    if not isinstance(root, _ALLOWED_ROOTS):
        raise UnsafeSQLError(
            f"only SELECT / WITH / VALUES queries are allowed (got {type(root).__name__.upper()})",
            code="not_select",
        )
    for node in stmt.walk():
        if isinstance(node, _FORBIDDEN_NODES):
            kind = type(node).__name__.upper()
            raise UnsafeSQLError(f"{kind} is not allowed in read-only SQL", code="forbidden_statement")
        if isinstance(node, exp.Func | exp.Anonymous):
            name = _func_name(node)
            if isinstance(node, _BLOCKED_FUNC_CLASSES) and name not in allow:
                raise UnsafeSQLError(
                    f"function {name or type(node).__name__} is not allowed", code="blocked_function"
                )
            if _is_blocked_function(name, allow, d):
                raise UnsafeSQLError(f"function {name} is not allowed", code="blocked_function")
        if isinstance(node, exp.Table | exp.Lateral):
            _check_table_function(node, allow)
        if isinstance(node, exp.Table):
            _check_table(node, d)
    try:
        return stmt.sql(dialect=d, comments=False)
    except Exception as exc:  # pragma: no cover - generator failure is a sqlglot bug
        raise UnsafeSQLError(f"could not regenerate SQL: {exc}", code="parse_error") from exc


def is_read_only(sql: str, dialect: str = "duckdb") -> bool:
    try:
        ensure_read_only(sql, dialect)
    except UnsafeSQLError:
        return False
    return True


def referenced_tables(sql: str, dialect: str = "duckdb") -> list[str]:
    """Physical tables referenced by a query (CTE names excluded)."""
    tree = sqlglot.parse_one(sql, read=_dialect(dialect))
    ctes = {c.alias_or_name for c in tree.find_all(exp.CTE)}
    out: list[str] = []
    for t in tree.find_all(exp.Table):
        if not t.name or t.name in ctes:
            continue
        if t.name not in out:
            out.append(t.name)
    return out


def _first_line(exc: Exception) -> str:
    return str(exc).splitlines()[0] if str(exc) else type(exc).__name__
