"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-18 08:08:25.593740
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import analystos_api.db

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_usage",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("task", sa.String(length=100), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("est_cost_usd", sa.Float(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage")),
    )
    with op.batch_alter_table("ai_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_usage_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=True),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("actor", sa.String(length=320), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_ws_created", ["workspace_id", "created_at"], unique=False)

    op.create_table(
        "diagnostic_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnostic_events")),
    )
    with op.batch_alter_table("diagnostic_events", schema=None) as batch_op:
        batch_op.create_index("ix_diag_ws_created", ["workspace_id", "created_at"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_local", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("revoked_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_workspaces_created_by_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
    )
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("read_only", sa.Boolean(), nullable=False),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("expires_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_api_tokens_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_tokens_token_hash")),
    )
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "dashboards",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("layout", sa.JSON(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("date_range", sa.JSON(), nullable=True),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_dashboards_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_dashboards_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboards")),
    )
    with op.batch_alter_table("dashboards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dashboards_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "data_sources",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("secrets_encrypted", sa.Text(), nullable=True),
        sa.Column("secret_fields", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_tested_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_test_message", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_data_sources_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_data_sources_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
    )
    with op.batch_alter_table("data_sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_data_sources_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "dimensions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_dimensions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dimensions")),
        sa.UniqueConstraint("workspace_id", "name", name=op.f("uq_dimensions_workspace_id")),
    )
    with op.batch_alter_table("dimensions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dimensions_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "entities",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_entities_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint("workspace_id", "name", name=op.f("uq_entities_workspace_id")),
    )
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entities_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "glossary_terms",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("term", sa.String(length=200), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_glossary_terms_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_glossary_terms_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_glossary_terms")),
        sa.UniqueConstraint("workspace_id", "term", name=op.f("uq_glossary_terms_workspace_id")),
    )
    with op.batch_alter_table("glossary_terms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_glossary_terms_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "investigations",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("template", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("metric_version_ids", sa.JSON(), nullable=False),
        sa.Column("dataset_versions", sa.JSON(), nullable=False),
        sa.Column("semantic_snapshot_id", sa.String(length=32), nullable=True),
        sa.Column("engine_version", sa.String(length=64), nullable=True),
        sa.Column("current_run_id", sa.String(length=32), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_investigations_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_investigations_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigations")),
    )
    with op.batch_alter_table("investigations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_investigations_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.String(length=32), nullable=True),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("started_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_jobs_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_jobs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "memberships",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_memberships_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint("workspace_id", "user_id", name=op.f("uq_memberships_workspace_id")),
    )
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memberships_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memberships_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "metric_trees",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("root_metric", sa.String(length=200), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_metric_trees_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_metric_trees_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_trees")),
        sa.UniqueConstraint("workspace_id", "root_metric", name=op.f("uq_metric_trees_workspace_id")),
    )
    with op.batch_alter_table("metric_trees", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_metric_trees_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "metrics",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("current_version_id", sa.String(length=32), nullable=True),
        sa.Column("current_version_no", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_metrics_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_metrics_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metrics")),
        sa.UniqueConstraint("workspace_id", "name", name=op.f("uq_metrics_workspace_id")),
    )
    with op.batch_alter_table("metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_metrics_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "notebooks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=True),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_notebooks_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_notebooks_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notebooks")),
    )
    with op.batch_alter_table("notebooks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notebooks_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "query_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("sql", sa.Text(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("saved_query_id", sa.String(length=32), nullable=True),
        sa.Column("data_source_id", sa.String(length=32), nullable=True),
        sa.Column("investigation_id", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("elapsed_ms", sa.Float(), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=False),
        sa.Column("result_snapshot", sa.JSON(), nullable=False),
        sa.Column("dataset_versions", sa.JSON(), nullable=False),
        sa.Column("metric_versions", sa.JSON(), nullable=False),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_query_runs_user_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_query_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_query_runs")),
    )
    with op.batch_alter_table("query_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_query_runs_workspace_id"), ["workspace_id"], unique=False)
        batch_op.create_index("ix_query_runs_ws_created", ["workspace_id", "created_at"], unique=False)

    op.create_table(
        "relationships",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("from_table", sa.String(length=200), nullable=False),
        sa.Column("from_col", sa.String(length=200), nullable=False),
        sa.Column("to_table", sa.String(length=200), nullable=False),
        sa.Column("to_col", sa.String(length=200), nullable=False),
        sa.Column("cardinality", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("signals", sa.JSON(), nullable=False),
        sa.Column("overlap_pct", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("join_analysis", sa.JSON(), nullable=True),
        sa.Column("decided_by", sa.String(length=32), nullable=True),
        sa.Column("decided_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["users.id"], name=op.f("fk_relationships_decided_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_relationships_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships")),
        sa.UniqueConstraint(
            "workspace_id",
            "from_table",
            "from_col",
            "to_table",
            "to_col",
            name=op.f("uq_relationships_workspace_id"),
        ),
    )
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_relationships_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "reports",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=True),
        sa.Column("investigation_id", sa.String(length=32), nullable=True),
        sa.Column("blocks", sa.JSON(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("published_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_reports_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_reports_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reports_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "saved_queries",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("sql", sa.Text(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("data_source_id", sa.String(length=32), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("chart", sa.JSON(), nullable=True),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_saved_queries_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_saved_queries_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_queries")),
    )
    with op.batch_alter_table("saved_queries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saved_queries_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "semantic_snapshots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("model", sa.JSON(), nullable=False),
        sa.Column("metric_version_ids", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_semantic_snapshots_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_semantic_snapshots_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semantic_snapshots")),
        sa.UniqueConstraint("workspace_id", "content_hash", name=op.f("uq_semantic_snapshots_workspace_id")),
    )
    with op.batch_alter_table("semantic_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_semantic_snapshots_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "stored_files",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("filename", sa.String(length=400), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=True),
        sa.Column("source_id", sa.String(length=32), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_stored_files_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_stored_files_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_files")),
    )
    with op.batch_alter_table("stored_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stored_files_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "uploads",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("filename", sa.String(length=400), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("file_kind", sa.String(length=16), nullable=False),
        sa.Column("inspection", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_uploads_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_uploads_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
    )
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_uploads_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=True),
        sa.Column("run_id", sa.String(length=32), nullable=True),
        sa.Column("engine_artifact_id", sa.String(length=64), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("sql", sa.Text(), nullable=True),
        sa.Column("python", sa.Text(), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("filter_context", sa.JSON(), nullable=False),
        sa.Column("metric_versions", sa.JSON(), nullable=False),
        sa.Column("dataset_versions", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("chart_spec", sa.JSON(), nullable=True),
        sa.Column("validation", sa.JSON(), nullable=True),
        sa.Column("parent_ids", sa.JSON(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_artifacts_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_artifacts_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_artifacts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifacts_investigation_id"), ["investigation_id"], unique=False)
        batch_op.create_index("ix_artifacts_run_engine", ["run_id", "engine_artifact_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "dashboard_tiles",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("dashboard_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("binding", sa.JSON(), nullable=False),
        sa.Column("viz", sa.JSON(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dashboard_id"],
            ["dashboards.id"],
            name=op.f("fk_dashboard_tiles_dashboard_id_dashboards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_tiles")),
    )
    with op.batch_alter_table("dashboard_tiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dashboard_tiles_dashboard_id"), ["dashboard_id"], unique=False)

    op.create_table(
        "dashboard_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("dashboard_id", sa.String(length=32), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_dashboard_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dashboard_id"],
            ["dashboards.id"],
            name=op.f("fk_dashboard_versions_dashboard_id_dashboards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_versions")),
        sa.UniqueConstraint("dashboard_id", "version_no", name=op.f("uq_dashboard_versions_dashboard_id")),
    )
    with op.batch_alter_table("dashboard_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dashboard_versions_dashboard_id"), ["dashboard_id"], unique=False
        )

    op.create_table(
        "datasets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("data_source_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("table_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.JSON(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=False),
        sa.Column("profile", sa.JSON(), nullable=True),
        sa.Column("profile_status", sa.String(length=32), nullable=False),
        sa.Column("profiled_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("current_version_id", sa.String(length=32), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_datasets_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_sources.id"],
            name=op.f("fk_datasets_data_source_id_data_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_datasets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datasets")),
        sa.UniqueConstraint("workspace_id", "table_name", name=op.f("uq_datasets_workspace_id")),
    )
    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_datasets_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=True),
        sa.Column("node_id", sa.String(length=64), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("statement_type", sa.String(length=32), nullable=False),
        sa.Column("evidence_strength", sa.String(length=32), nullable=False),
        sa.Column("evidence_reasons", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("business_impact", sa.Text(), nullable=False),
        sa.Column("metric_id", sa.String(length=200), nullable=True),
        sa.Column("metric_version_ids", sa.JSON(), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("filter_context", sa.JSON(), nullable=False),
        sa.Column("segment", sa.JSON(), nullable=True),
        sa.Column("artifact_ids", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_findings_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_findings_investigation_id_investigations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_findings_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_findings_investigation_id"), ["investigation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_findings_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "investigation_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("investigation_id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("run_no", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("metric_version_ids", sa.JSON(), nullable=False),
        sa.Column("dataset_versions", sa.JSON(), nullable=False),
        sa.Column("semantic_snapshot_id", sa.String(length=32), nullable=True),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("triggered_by", sa.String(length=32), nullable=True),
        sa.Column("started_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("finished_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name=op.f("fk_investigation_runs_investigation_id_investigations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["users.id"],
            name=op.f("fk_investigation_runs_triggered_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_investigation_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigation_runs")),
        sa.UniqueConstraint(
            "investigation_id", "run_no", name=op.f("uq_investigation_runs_investigation_id")
        ),
    )
    with op.batch_alter_table("investigation_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_investigation_runs_investigation_id"), ["investigation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_investigation_runs_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "metric_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("metric_id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("change_note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_metric_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["metrics.id"],
            name=op.f("fk_metric_versions_metric_id_metrics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_metric_versions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_versions")),
        sa.UniqueConstraint("metric_id", "version_no", name=op.f("uq_metric_versions_metric_id")),
    )
    with op.batch_alter_table("metric_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_metric_versions_metric_id"), ["metric_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_metric_versions_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "notebook_cells",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("notebook_id", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("execution_count", sa.Integer(), nullable=False),
        sa.Column("last_run_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["notebook_id"],
            ["notebooks.id"],
            name=op.f("fk_notebook_cells_notebook_id_notebooks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notebook_cells")),
    )
    with op.batch_alter_table("notebook_cells", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notebook_cells_notebook_id"), ["notebook_id"], unique=False)

    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("dataset_id", sa.String(length=32), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=False),
        sa.Column("ingest_options", sa.JSON(), nullable=False),
        sa.Column("upload_id", sa.String(length=32), nullable=True),
        sa.Column("captured_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_dataset_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_dataset_versions_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("fk_dataset_versions_upload_id_uploads"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_versions")),
        sa.UniqueConstraint("dataset_id", "version_no", name=op.f("uq_dataset_versions_dataset_id")),
    )
    with op.batch_alter_table("dataset_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dataset_versions_dataset_id"), ["dataset_id"], unique=False)

    op.create_table(
        "finding_comments",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("finding_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_finding_comments_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_finding_comments_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_comments")),
    )
    with op.batch_alter_table("finding_comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_finding_comments_finding_id"), ["finding_id"], unique=False)

    op.create_table(
        "finding_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("finding_id", sa.String(length=32), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("change_note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_finding_versions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_finding_versions_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_versions")),
        sa.UniqueConstraint("finding_id", "version_no", name=op.f("uq_finding_versions_finding_id")),
    )
    with op.batch_alter_table("finding_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_finding_versions_finding_id"), ["finding_id"], unique=False)

    op.create_table(
        "quality_rules",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("dataset_id", sa.String(length=32), nullable=True),
        sa.Column("table_name", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("column", sa.String(length=200), nullable=True),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("last_run_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_passed", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_quality_rules_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_quality_rules_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_quality_rules_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_rules")),
    )
    with op.batch_alter_table("quality_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quality_rules_dataset_id"), ["dataset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quality_rules_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "quality_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("failing_count", sa.Integer(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=True),
        sa.Column("sample_failing_rows", sa.JSON(), nullable=False),
        sa.Column("sql", sa.Text(), nullable=False),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("dataset_version_id", sa.String(length=32), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("run_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["quality_rules.id"],
            name=op.f("fk_quality_runs_rule_id_quality_rules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_by"], ["users.id"], name=op.f("fk_quality_runs_run_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_quality_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_runs")),
    )
    with op.batch_alter_table("quality_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quality_runs_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_quality_runs_workspace_id"), ["workspace_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quality_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quality_runs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_quality_runs_rule_id"))

    op.drop_table("quality_runs")
    with op.batch_alter_table("quality_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quality_rules_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_quality_rules_dataset_id"))

    op.drop_table("quality_rules")
    with op.batch_alter_table("finding_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finding_versions_finding_id"))

    op.drop_table("finding_versions")
    with op.batch_alter_table("finding_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_finding_comments_finding_id"))

    op.drop_table("finding_comments")
    with op.batch_alter_table("dataset_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dataset_versions_dataset_id"))

    op.drop_table("dataset_versions")
    with op.batch_alter_table("notebook_cells", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notebook_cells_notebook_id"))

    op.drop_table("notebook_cells")
    with op.batch_alter_table("metric_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metric_versions_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_metric_versions_metric_id"))

    op.drop_table("metric_versions")
    with op.batch_alter_table("investigation_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investigation_runs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_investigation_runs_investigation_id"))

    op.drop_table("investigation_runs")
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_findings_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_findings_investigation_id"))

    op.drop_table("findings")
    with op.batch_alter_table("datasets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_datasets_workspace_id"))

    op.drop_table("datasets")
    with op.batch_alter_table("dashboard_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dashboard_versions_dashboard_id"))

    op.drop_table("dashboard_versions")
    with op.batch_alter_table("dashboard_tiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dashboard_tiles_dashboard_id"))

    op.drop_table("dashboard_tiles")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifacts_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_run_id"))
        batch_op.drop_index("ix_artifacts_run_engine")
        batch_op.drop_index(batch_op.f("ix_artifacts_investigation_id"))

    op.drop_table("artifacts")
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uploads_workspace_id"))

    op.drop_table("uploads")
    with op.batch_alter_table("stored_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stored_files_workspace_id"))

    op.drop_table("stored_files")
    with op.batch_alter_table("semantic_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_semantic_snapshots_workspace_id"))

    op.drop_table("semantic_snapshots")
    with op.batch_alter_table("saved_queries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_queries_workspace_id"))

    op.drop_table("saved_queries")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reports_workspace_id"))

    op.drop_table("reports")
    with op.batch_alter_table("relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_relationships_workspace_id"))

    op.drop_table("relationships")
    with op.batch_alter_table("query_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_query_runs_ws_created")
        batch_op.drop_index(batch_op.f("ix_query_runs_workspace_id"))

    op.drop_table("query_runs")
    with op.batch_alter_table("notebooks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notebooks_workspace_id"))

    op.drop_table("notebooks")
    with op.batch_alter_table("metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metrics_workspace_id"))

    op.drop_table("metrics")
    with op.batch_alter_table("metric_trees", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metric_trees_workspace_id"))

    op.drop_table("metric_trees")
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memberships_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_memberships_user_id"))

    op.drop_table("memberships")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_workspace_id"))

    op.drop_table("jobs")
    with op.batch_alter_table("investigations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_investigations_workspace_id"))

    op.drop_table("investigations")
    with op.batch_alter_table("glossary_terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_glossary_terms_workspace_id"))

    op.drop_table("glossary_terms")
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entities_workspace_id"))

    op.drop_table("entities")
    with op.batch_alter_table("dimensions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dimensions_workspace_id"))

    op.drop_table("dimensions")
    with op.batch_alter_table("data_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_data_sources_workspace_id"))

    op.drop_table("data_sources")
    with op.batch_alter_table("dashboards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dashboards_workspace_id"))

    op.drop_table("dashboards")
    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_tokens_user_id"))

    op.drop_table("api_tokens")
    op.drop_table("workspaces")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_user_id"))

    op.drop_table("auth_sessions")
    op.drop_table("users")
    with op.batch_alter_table("diagnostic_events", schema=None) as batch_op:
        batch_op.drop_index("ix_diag_ws_created")

    op.drop_table("diagnostic_events")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_ws_created")

    op.drop_table("audit_log")
    with op.batch_alter_table("ai_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_usage_workspace_id"))

    op.drop_table("ai_usage")
    # ### end Alembic commands ###
