"""workspace invites

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-18 17:04:19.661412
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import analystos_api.db

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invites",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("workspace_id", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", analystos_api.db.UTCDateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.Column("accepted_by", sa.String(length=32), nullable=True),
        sa.Column("revoked_at", analystos_api.db.UTCDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["accepted_by"], ["users.id"], name=op.f("fk_invites_accepted_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_invites_created_by_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_invites_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invites")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invites_token_hash")),
    )
    with op.batch_alter_table("invites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invites_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_invites_workspace_id"), ["workspace_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invites_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_invites_email"))

    op.drop_table("invites")
    # ### end Alembic commands ###
