"""Attribution arithmetic used to build contribution and driver nodes.

The SQL that produces the inputs is always generated by the engine's semantic compiler;
this module only does the arithmetic on the validated results so that the tree semantics
(shares, residuals, additivity) are defined in one place.

Methods
-------
``additive``
    Metric aggregates are sums or counts that partition across the dimension's segments.
    Additivity is *verified on the data*: the segment values must add up to the total in
    both periods. Effect of segment i is ``cur_i - base_i``; share is effect / total change.
    Shares sum to 1 within the dimension.
``ratio_mix_rate``
    Ratio metrics R = N / D (e.g. AOV = Revenue / Orders). With weights ``w_i = D_i / D`` and
    segment rates ``r_i = N_i / D_i``, R = sum(w_i r_i). The change splits exactly into a
    rate effect ``mean(w_i) * (r_i1 - r_i0)`` and a mix effect ``(w_i1 - w_i0) * (mean(r_i) - mean(R))``.
    The mix term is centred on the average total rate, so moving weight toward an
    above-average segment is a positive mix effect. The centring term sums to zero across
    segments, so the effects still sum exactly to the total change.
``non_additive``
    Segments do not partition the total (count-distinct entities shared across segments,
    averages, min/max). Segment moves are reported but no share is claimed.

Driver decomposition
--------------------
``lmdi``
    Multiplicative identities (Revenue = Orders x AOV) use the additive log-mean Divisia
    index: effect_k = L(V1, V0) * ln(x_k1 / x_k0) where L(a, b) = (a - b) / (ln a - ln b).
    Effects sum exactly to V1 - V0 when the identity holds. Ratio identities use exponent
    -1 for the denominator.
``additive_identity``
    Additive/subtractive identities (Margin = Revenue - COGS): effect = sign * change.
Any gap between the identity and the observed parent value is reported as a residual.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

EPS = 1e-12


def _num(v: object) -> float:
    if v is None:
        return 0.0
    try:
        f = float(v)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return 0.0
    return 0.0 if math.isnan(f) else f


def safe_pct(cur: float | None, base: float | None) -> float | None:
    if cur is None or base is None or abs(base) < EPS:
        return None
    return (cur - base) / abs(base)


def safe_share(effect: float, total_change: float) -> float | None:
    if abs(total_change) < EPS:
        return None
    return effect / total_change


@dataclass
class SegmentRow:
    value: str | None
    current: float | None
    baseline: float | None
    effect: float
    share: float | None
    mix_effect: float | None = None
    rate_effect: float | None = None
    base_share: float | None = None

    @property
    def abs_change(self) -> float | None:
        if self.current is None and self.baseline is None:
            return None
        return _num(self.current) - _num(self.baseline)

    @property
    def pct_change(self) -> float | None:
        return safe_pct(self.current, self.baseline)


@dataclass
class ContributionOutcome:
    method: str
    total_current: float | None
    total_baseline: float | None
    total_change: float | None
    rows: list[SegmentRow]
    additive_valid: bool
    notes: list[str] = field(default_factory=list)
    partition_gap: float | None = None

    def ranked(self) -> list[SegmentRow]:
        """Rows by |share| (or |effect| when shares are undefined), ties broken by value."""

        def key(r: SegmentRow) -> tuple[float, float, str]:
            s = abs(r.share) if r.share is not None else -1.0
            return (-s, -abs(r.effect), "" if r.value is None else str(r.value))

        return sorted(self.rows, key=key)


def _merge(
    current: dict[str | None, float], baseline: dict[str | None, float]
) -> list[tuple[str | None, float, float]]:
    """Align segments across periods. For sum/count aggregates a segment with no rows in a
    period has the value 0 in that period (it sold nothing), so missing becomes 0.0."""
    keys = sorted(set(current) | set(baseline), key=lambda k: (k is None, "" if k is None else str(k)))
    return [(k, _num(current.get(k)), _num(baseline.get(k))) for k in keys]


def additive_contribution(
    current: dict[str | None, float],
    baseline: dict[str | None, float],
    total_current: float,
    total_baseline: float,
    *,
    tolerance: float = 1e-6,
) -> ContributionOutcome:
    """Segment contribution for sum/count style metrics, with an empirical partition check."""
    sum_cur = sum(_num(v) for v in current.values())
    sum_base = sum(_num(v) for v in baseline.values())
    scale = max(abs(total_current), abs(total_baseline), 1.0)
    gap = max(abs(sum_cur - total_current), abs(sum_base - total_baseline))
    partition = gap <= tolerance * scale + 1e-9
    total_change = total_current - total_baseline
    rows: list[SegmentRow] = []
    notes: list[str] = []
    if partition:
        for key, cur, base in _merge(current, baseline):
            effect = _num(cur) - _num(base)
            rows.append(
                SegmentRow(
                    value=key,
                    current=cur,
                    baseline=base,
                    effect=effect,
                    share=safe_share(effect, total_change),
                    base_share=(_num(base) / total_baseline) if abs(total_baseline) > EPS else None,
                )
            )
        if abs(total_change) < EPS:
            notes.append("total change is zero, so shares of change are undefined")
        return ContributionOutcome("additive", total_current, total_baseline, total_change, rows, True, notes)
    for key, cur, base in _merge(current, baseline):
        rows.append(
            SegmentRow(
                value=key,
                current=cur,
                baseline=base,
                effect=_num(cur) - _num(base),
                share=None,
                base_share=(_num(base) / total_baseline) if abs(total_baseline) > EPS else None,
            )
        )
    notes.append(
        "segments do not partition the total (segment values sum to "
        f"{sum_cur:,.2f} vs total {total_current:,.2f}); entities appear in several segments, "
        "so no share of change is claimed"
    )
    return ContributionOutcome(
        "non_additive", total_current, total_baseline, total_change, rows, False, notes, partition_gap=gap
    )


def ratio_contribution(
    num_current: dict[str | None, float],
    den_current: dict[str | None, float],
    num_baseline: dict[str | None, float],
    den_baseline: dict[str | None, float],
    *,
    totals: tuple[float, float, float, float] | None = None,
    tolerance: float = 1e-6,
) -> ContributionOutcome:
    """Mix/rate decomposition of a ratio metric R = N / D across segments.

    The decomposition is only valid when the segments partition both the numerator and the
    denominator. ``totals`` = (N_current, D_current, N_baseline, D_baseline) measured without
    the breakdown; when given, the segment sums must match them in both periods, otherwise
    the segments overlap (AOV by product category: one order spans several categories) and
    the result is ``non_additive``: segment ratios are reported, no share is claimed.
    """
    n1 = sum(_num(v) for v in num_current.values())
    d1 = sum(_num(v) for v in den_current.values())
    n0 = sum(_num(v) for v in num_baseline.values())
    d0 = sum(_num(v) for v in den_baseline.values())
    notes: list[str] = []
    if totals is not None:
        tn1, td1, tn0, td0 = (_num(x) for x in totals)
        gaps = [abs(a - b) / max(abs(b), 1.0) for a, b in ((n1, tn1), (d1, td1), (n0, tn0), (d0, td0))]
        if max(gaps) > tolerance:
            return _overlapping_ratio(
                num_current, den_current, num_baseline, den_baseline, (tn1, td1, tn0, td0), (n1, d1, n0, d0)
            )
    if abs(d1) < EPS or abs(d0) < EPS:
        return ContributionOutcome(
            "non_additive",
            None,
            None,
            None,
            [],
            False,
            ["denominator is zero in one period, so the ratio cannot be decomposed"],
        )
    r1, r0 = n1 / d1, n0 / d0
    r_bar = (r1 + r0) / 2
    total_change = r1 - r0
    keys = sorted(
        set(num_current) | set(den_current) | set(num_baseline) | set(den_baseline),
        key=lambda k: (k is None, "" if k is None else str(k)),
    )
    rows: list[SegmentRow] = []
    for k in keys:
        dc, db = _num(den_current.get(k)), _num(den_baseline.get(k))
        nc, nb = _num(num_current.get(k)), _num(num_baseline.get(k))
        w1, w0 = dc / d1, db / d0
        rate1 = nc / dc if abs(dc) > EPS else None
        rate0 = nb / db if abs(db) > EPS else None
        if rate1 is None and rate0 is None:
            continue
        # A segment present in only one period has no rate change; all of its effect is mix.
        ra = rate1 if rate1 is not None else rate0
        rb = rate0 if rate0 is not None else rate1
        assert ra is not None and rb is not None
        rate_effect = (w1 + w0) / 2 * (ra - rb)
        mix_effect = (w1 - w0) * ((ra + rb) / 2 - r_bar)
        effect = rate_effect + mix_effect
        rows.append(
            SegmentRow(
                value=k,
                current=rate1,
                baseline=rate0,
                effect=effect,
                share=safe_share(effect, total_change),
                mix_effect=mix_effect,
                rate_effect=rate_effect,
                base_share=w0,
            )
        )
    if abs(total_change) < EPS:
        notes.append("ratio is unchanged, so shares of change are undefined")
    return ContributionOutcome("ratio_mix_rate", r1, r0, total_change, rows, True, notes)


def _overlapping_ratio(
    num_current: dict[str | None, float],
    den_current: dict[str | None, float],
    num_baseline: dict[str | None, float],
    den_baseline: dict[str | None, float],
    totals: tuple[float, float, float, float],
    sums: tuple[float, float, float, float],
) -> ContributionOutcome:
    tn1, td1, tn0, td0 = totals
    n1, d1, n0, d0 = sums
    r1 = tn1 / td1 if abs(td1) > EPS else None
    r0 = tn0 / td0 if abs(td0) > EPS else None
    keys = sorted(
        set(num_current) | set(den_current) | set(num_baseline) | set(den_baseline),
        key=lambda k: (k is None, "" if k is None else str(k)),
    )
    rows: list[SegmentRow] = []
    for k in keys:
        dc, db = _num(den_current.get(k)), _num(den_baseline.get(k))
        rate1 = _num(num_current.get(k)) / dc if abs(dc) > EPS else None
        rate0 = _num(num_baseline.get(k)) / db if abs(db) > EPS else None
        if rate1 is None and rate0 is None:
            continue
        rows.append(
            SegmentRow(
                value=k,
                current=rate1,
                baseline=rate0,
                effect=_num(rate1) - _num(rate0) if rate1 is not None and rate0 is not None else 0.0,
                share=None,
                base_share=(db / td0) if abs(td0) > EPS else None,
            )
        )
    note = (
        "segments overlap: they sum to "
        f"{d1:,.0f} (current) and {d0:,.0f} (baseline) in the denominator against true totals of "
        f"{td1:,.0f} and {td0:,.0f}, so the ratio cannot be split into segment shares; each segment's own "
        "ratio is shown instead"
    )
    if abs(n1 - tn1) > EPS * max(abs(tn1), 1.0) and abs(d1 - td1) <= EPS * max(abs(td1), 1.0):
        note = "segments do not partition the numerator; " + note
    change = (r1 - r0) if r1 is not None and r0 is not None else None
    return ContributionOutcome("non_additive", r1, r0, change, rows, False, [note])


# --------------------------------------------------------------------------- driver identities


def log_mean(a: float, b: float) -> float:
    if a <= 0 or b <= 0:
        raise ValueError("log-mean requires positive values")
    if abs(a - b) < EPS * max(abs(a), 1.0):
        return a
    return (a - b) / (math.log(a) - math.log(b))


@dataclass
class DriverEffect:
    metric_id: str
    relation: str
    current: float
    baseline: float
    effect: float
    share: float | None


@dataclass
class DecompositionOutcome:
    method: str
    parent_current: float
    parent_baseline: float
    parent_change: float
    effects: list[DriverEffect]
    identity_current: float | None
    identity_baseline: float | None
    residual: float
    residual_share: float | None
    notes: list[str] = field(default_factory=list)
    valid: bool = True


def decompose_drivers(
    parent_current: float,
    parent_baseline: float,
    drivers: list[tuple[str, str, float, float]],
) -> DecompositionOutcome:
    """Split a parent change across its drivers.

    ``drivers`` holds ``(metric_id, relation, current, baseline)`` with relation one of
    ``multiplicative``, ``ratio_numerator``, ``ratio_denominator``, ``additive`` or
    ``subtractive``. Multiplicative/ratio relations must not be mixed with additive ones in
    one identity; the caller splits the tree edges by relation family.
    """
    change = parent_current - parent_baseline
    relations = {r for _, r, _, _ in drivers}
    multiplicative = relations <= {"multiplicative", "ratio_numerator", "ratio_denominator"}
    additive = relations <= {"additive", "subtractive"}
    notes: list[str] = []
    if not drivers or not (multiplicative or additive):
        return DecompositionOutcome(
            "none",
            parent_current,
            parent_baseline,
            change,
            [],
            None,
            None,
            change,
            None,
            ["driver relations mix additive and multiplicative forms; no exact identity"],
            False,
        )

    effects: list[DriverEffect] = []
    if multiplicative:
        ident_c = 1.0
        ident_b = 1.0
        for _, rel, c, b in drivers:
            exp = -1.0 if rel == "ratio_denominator" else 1.0
            if c <= 0 or b <= 0:
                return DecompositionOutcome(
                    "lmdi",
                    parent_current,
                    parent_baseline,
                    change,
                    [],
                    None,
                    None,
                    change,
                    None,
                    ["a driver is zero or negative, so the log decomposition is undefined"],
                    False,
                )
            ident_c *= c**exp
            ident_b *= b**exp
        if ident_c <= 0 or ident_b <= 0:
            return DecompositionOutcome(
                "lmdi",
                parent_current,
                parent_baseline,
                change,
                [],
                ident_c,
                ident_b,
                change,
                None,
                ["identity value is not positive"],
                False,
            )
        lm = log_mean(ident_c, ident_b)
        for mid, rel, c, b in drivers:
            exp = -1.0 if rel == "ratio_denominator" else 1.0
            eff = lm * exp * math.log(c / b)
            effects.append(DriverEffect(mid, rel, c, b, eff, safe_share(eff, change)))
        method = "lmdi"
    else:
        ident_c = 0.0
        ident_b = 0.0
        for mid, rel, c, b in drivers:
            sign = -1.0 if rel == "subtractive" else 1.0
            ident_c += sign * c
            ident_b += sign * b
            eff = sign * (c - b)
            effects.append(DriverEffect(mid, rel, c, b, eff, safe_share(eff, change)))
        method = "additive_identity"

    explained = sum(e.effect for e in effects)
    residual = change - explained
    residual_share = safe_share(residual, change)
    scale = max(abs(parent_current), abs(parent_baseline), 1.0)
    identity_gap = max(abs(ident_c - parent_current), abs(ident_b - parent_baseline)) / scale
    if identity_gap > 1e-6:
        notes.append(
            f"driver identity reproduces the parent within {identity_gap * 100:.2f}% "
            "(differences come from metric filters or rounding in definitions)"
        )
    return DecompositionOutcome(
        method,
        parent_current,
        parent_baseline,
        change,
        effects,
        ident_c,
        ident_b,
        residual,
        residual_share,
        notes,
        True,
    )
