/** Centralized TanStack Query keys: `[workspace, resource, ...params]` so invalidation by prefix works. */
export const qk = {
  session: ["session"] as const,
  workspaces: ["workspaces"] as const,
  workspace: (ws: string) => ["ws", ws] as const,
  home: (ws: string) => ["ws", ws, "home"] as const,
  members: (ws: string) => ["ws", ws, "members"] as const,
  tokens: ["tokens"] as const,
  dataSources: (ws: string) => ["ws", ws, "data-sources"] as const,
  connectorKinds: ["connector-kinds"] as const,
  datasets: (ws: string) => ["ws", ws, "datasets"] as const,
  dataset: (ws: string, id: string) => ["ws", ws, "datasets", id] as const,
  datasetPart: (ws: string, id: string, part: string, extra?: unknown) =>
    ["ws", ws, "datasets", id, part, extra ?? null] as const,
  relationships: (ws: string, params?: unknown) => ["ws", ws, "relationships", params ?? null] as const,
  qualityRules: (ws: string, params?: unknown) => ["ws", ws, "quality", "rules", params ?? null] as const,
  qualityRuns: (ws: string, params?: unknown) => ["ws", ws, "quality", "runs", params ?? null] as const,
  qualityRun: (ws: string, id: string) => ["ws", ws, "quality", "run", id] as const,
  semantic: (ws: string, part: string) => ["ws", ws, "semantic", part] as const,
  metrics: (ws: string) => ["ws", ws, "metrics"] as const,
  metric: (ws: string, id: string) => ["ws", ws, "metrics", id] as const,
  metricPart: (ws: string, id: string, part: string, extra?: unknown) =>
    ["ws", ws, "metrics", id, part, extra ?? null] as const,
  dimensions: (ws: string) => ["ws", ws, "dimensions"] as const,
  dimensionValues: (ws: string, name: string, q?: string) => ["ws", ws, "dimensions", name, "values", q ?? ""] as const,
  metricTrees: (ws: string) => ["ws", ws, "metric-trees"] as const,
  glossary: (ws: string) => ["ws", ws, "glossary"] as const,
  queryHistory: (ws: string, params?: unknown) => ["ws", ws, "queries", "history", params ?? null] as const,
  savedQueries: (ws: string) => ["ws", ws, "queries", "saved"] as const,
  savedQuery: (ws: string, id: string) => ["ws", ws, "queries", "saved", id] as const,
  schema: (ws: string, source?: string | null) => ["ws", ws, "queries", "schema", source ?? null] as const,
  notebooks: (ws: string) => ["ws", ws, "notebooks"] as const,
  notebook: (ws: string, id: string) => ["ws", ws, "notebooks", id] as const,
  investigations: (ws: string, params?: unknown) => ["ws", ws, "investigations", "list", params ?? null] as const,
  investigation: (ws: string, id: string) => ["ws", ws, "investigations", id] as const,
  investigationPart: (ws: string, id: string, part: string, extra?: unknown) =>
    ["ws", ws, "investigations", id, part, extra ?? null] as const,
  templates: (ws: string) => ["ws", ws, "investigation-templates"] as const,
  artifact: (ws: string, id: string) => ["ws", ws, "artifacts", id] as const,
  artifactLineage: (ws: string, id: string) => ["ws", ws, "artifacts", id, "lineage"] as const,
  findings: (ws: string, params?: unknown) => ["ws", ws, "findings", "list", params ?? null] as const,
  finding: (ws: string, id: string) => ["ws", ws, "findings", id] as const,
  findingPart: (ws: string, id: string, part: string) => ["ws", ws, "findings", id, part] as const,
  dashboards: (ws: string) => ["ws", ws, "dashboards"] as const,
  dashboard: (ws: string, id: string) => ["ws", ws, "dashboards", id] as const,
  tileData: (ws: string, dashboardId: string, tileId: string, ctx: unknown) =>
    ["ws", ws, "dashboards", dashboardId, "tile", tileId, ctx] as const,
  reports: (ws: string, params?: unknown) => ["ws", ws, "reports", "list", params ?? null] as const,
  report: (ws: string, id: string) => ["ws", ws, "reports", id] as const,
  search: (ws: string, q: string) => ["ws", ws, "search", q] as const,
  aiSettings: (ws: string) => ["ws", ws, "ai", "settings"] as const,
  aiUsage: (ws: string, days: number) => ["ws", ws, "ai", "usage", days] as const,
  diagnostics: ["diagnostics"] as const,
  events: (ws: string | null, params?: unknown) => ["events", ws, params ?? null] as const,
  audit: (ws: string, params?: unknown) => ["ws", ws, "audit", params ?? null] as const,
  analyses: (ws: string, kind?: string) => ["ws", ws, "analysis", "list", kind ?? null] as const,
  demo: ["demo"] as const,
};
